name: standby
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  battery_plus: ^6.0.3
  bloc: ^8.1.4
  cupertino_clock: ^0.1.0+1
  device_calendar: ^4.3.2
  firebase_analytics: ^11.3.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_timezone: ^3.0.1
  get_it: ^7.7.0
  go_router: ^14.2.7
  intl: ^0.19.0
  meta: ^1.15.0
  wakelock_plus: ^1.2.8
  weatherapi: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
