// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCR4ZfU_eYCl9ud6BrBvj-rnBG9ZedyRg',
    appId: '1:732172910549:web:a9ae80ee7c1bf20b0b475c',
    messagingSenderId: '732172910549',
    projectId: 'standby-flutter',
    authDomain: 'standby-flutter.firebaseapp.com',
    storageBucket: 'standby-flutter.appspot.com',
    measurementId: 'G-0M30KGJWEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpszUKwZnevwaKFyQjWSiAWoP9HxN20Ro',
    appId: '1:732172910549:android:7ae2d0ee9916be470b475c',
    messagingSenderId: '732172910549',
    projectId: 'standby-flutter',
    storageBucket: 'standby-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzbDO691rddbn6I4BhCwoYhtBUC9VYZjQ',
    appId: '1:732172910549:ios:c07b603d35f5c9eb0b475c',
    messagingSenderId: '732172910549',
    projectId: 'standby-flutter',
    storageBucket: 'standby-flutter.appspot.com',
    iosBundleId: 'dev.aquiles.standby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzbDO691rddbn6I4BhCwoYhtBUC9VYZjQ',
    appId: '1:732172910549:ios:c07b603d35f5c9eb0b475c',
    messagingSenderId: '732172910549',
    projectId: 'standby-flutter',
    storageBucket: 'standby-flutter.appspot.com',
    iosBundleId: 'dev.aquiles.standby',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCR4ZfU_eYCl9ud6BrBvj-rnBG9ZedyRg',
    appId: '1:732172910549:web:df31cbd67735c3240b475c',
    messagingSenderId: '732172910549',
    projectId: 'standby-flutter',
    authDomain: 'standby-flutter.firebaseapp.com',
    storageBucket: 'standby-flutter.appspot.com',
    measurementId: 'G-XNVM125QB7',
  );

}